CREATE TABLE game (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR,
  year INT,
  rank INT,
  average FLOAT,
  Bayes_Average FLOAT,
  Users_Rated INT,
  url VARCHAR,
  thumbnail VARCHAR
);

CREATE TABLE review (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id VARCHAR,
  rating FLOAT,
  comment VARCHAR,
  game_id INT REFERENCES game
(id)
);